package storage

import "context"

// The editable navigation, both storeys of it: GROUPS are the dropdowns of
// the top bar and the link columns of the footer — each with a default
// label, an optional message-catalogue slug that localises that label per
// viewer, an icon, an order and a placement — and ENTRIES are the links
// inside them. WordPress's Menus screen, including the part WordPress does
// with theme "locations": a group is assignable to the top bar or the
// footer, whole.
//
// Built-in rows (groups and entries alike) are ENSURED, not seeded: every
// boot inserts what is missing by KEY and touches nothing that exists, so a
// newly shipped link reaches old databases while operator edits survive.
// The code-side defaults (navadmin_web.go) double as the render fallback
// when these tables cannot be read — a broken settings table must degrade
// to the shipped menu, never to a site with no navigation.

// NavGroup is one dropdown or footer column.
type NavGroup struct {
	Key   string `db:"key"`
	Label string `db:"label"`
	// LabelSlug names a message-catalogue entry (i18n_messages); when set
	// and resolvable for the viewer it REPLACES Label, which stays the
	// fallback for every locale the slug does not cover.
	LabelSlug string `db:"label_slug"`
	Icon      string `db:"icon"`
	Ordinal   int    `db:"ordinal"`
	Hidden    bool   `db:"hidden"`
	// Placement is "top" (a dropdown tab) or "footer" (a link column).
	Placement string `db:"placement"`
	Builtin   bool   `db:"builtin"`
}

// NavEntry is one link. ID is the row's form identity; Key is the builtin
// reconciliation identity ("top:/browse", "footer:/browse" — the same href
// may sit in both storeys) and empty for operator-added rows.
type NavEntry struct {
	ID      int64  `db:"id"`
	Key     string `db:"key"`
	Href    string `db:"href"`
	Label   string `db:"label"`
	Grp     string `db:"grp"`
	Ordinal int    `db:"ordinal"`
	Hidden  bool   `db:"hidden"`
	Builtin bool   `db:"builtin"`
}

// MigrateSiteNav creates both tables, and lifts a v1 site_nav (href as
// primary key, no groups table — shipped the day before this) to v2 in
// place: id becomes the identity, key the builtin anchor. Guarded column by
// column, so it is idempotent and a fresh database takes the CREATE path.
func (st *Store) MigrateSiteNav() error {
	if _, err := st.db.Exec(`CREATE TABLE IF NOT EXISTS site_nav_groups (
	    key       TEXT PRIMARY KEY,
	    label     TEXT NOT NULL,
	    label_slug TEXT NOT NULL DEFAULT '',
	    icon      TEXT NOT NULL DEFAULT '',
	    ordinal   INT NOT NULL DEFAULT 0,
	    hidden    BOOLEAN NOT NULL DEFAULT FALSE,
	    placement TEXT NOT NULL DEFAULT 'top',
	    builtin   BOOLEAN NOT NULL DEFAULT FALSE
	)`); err != nil {
		return err
	}
	if _, err := st.db.Exec(`CREATE TABLE IF NOT EXISTS site_nav (
	    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	    key     TEXT NOT NULL DEFAULT '',
	    href    TEXT NOT NULL,
	    label   TEXT NOT NULL,
	    grp     TEXT NOT NULL,
	    ordinal INT NOT NULL DEFAULT 0,
	    hidden  BOOLEAN NOT NULL DEFAULT FALSE,
	    builtin BOOLEAN NOT NULL DEFAULT FALSE
	)`); err != nil {
		return err
	}
	// The v1 lift. A v1 table lacks id; these are no-ops everywhere else.
	if _, err := st.db.Exec(`ALTER TABLE site_nav
	    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY`); err != nil {
		return err
	}
	if _, err := st.db.Exec(`ALTER TABLE site_nav
	    ADD COLUMN IF NOT EXISTS key TEXT NOT NULL DEFAULT ''`); err != nil {
		return err
	}
	// Swap the primary key from href to id, once: the guard asks whether the
	// PK still covers href, which is only true of a v1 table.
	if _, err := st.db.Exec(`DO $$ BEGIN
	    IF EXISTS (
	        SELECT 1 FROM pg_constraint c
	        JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
	        WHERE c.conname = 'site_nav_pkey'
	          AND c.conrelid = 'site_nav'::regclass
	          AND a.attname = 'href'
	    ) THEN
	        ALTER TABLE site_nav DROP CONSTRAINT site_nav_pkey;
	        ALTER TABLE site_nav ADD PRIMARY KEY (id);
	    END IF;
	END $$`); err != nil {
		return err
	}
	// v1 builtin rows get their v2 keys, so the ensure pass recognises them
	// instead of inserting twins. v1 held only top-bar entries.
	_, err := st.db.Exec(`UPDATE site_nav SET key = 'top:' || href
	    WHERE builtin AND key = ''`)
	return err
}

// ── groups ──────────────────────────────────────────────────────────────

// ListSiteNavGroups returns every group, ordinal-ordered.
func (st *Store) ListSiteNavGroups(ctx context.Context) ([]NavGroup, error) {
	var out []NavGroup
	err := st.db.SelectContext(ctx, &out,
		`SELECT key, label, label_slug, icon, ordinal, hidden, placement, builtin
		   FROM site_nav_groups ORDER BY ordinal, key`)
	return out, err
}

// EnsureSiteNavGroup inserts a group only if its key is absent.
func (st *Store) EnsureSiteNavGroup(ctx context.Context, g NavGroup) error {
	_, err := st.db.ExecContext(ctx, `
		INSERT INTO site_nav_groups (key, label, label_slug, icon, ordinal, hidden, placement, builtin)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		ON CONFLICT (key) DO NOTHING`,
		g.Key, g.Label, g.LabelSlug, g.Icon, g.Ordinal, g.Hidden, g.Placement, g.Builtin)
	return err
}

// UpsertSiteNavGroup writes a group outright.
func (st *Store) UpsertSiteNavGroup(ctx context.Context, g NavGroup) error {
	_, err := st.db.ExecContext(ctx, `
		INSERT INTO site_nav_groups (key, label, label_slug, icon, ordinal, hidden, placement, builtin)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label,
		    label_slug = EXCLUDED.label_slug, icon = EXCLUDED.icon,
		    ordinal = EXCLUDED.ordinal, hidden = EXCLUDED.hidden,
		    placement = EXCLUDED.placement, builtin = EXCLUDED.builtin`,
		g.Key, g.Label, g.LabelSlug, g.Icon, g.Ordinal, g.Hidden, g.Placement, g.Builtin)
	return err
}

// DeleteSiteNavGroup removes a group. The editor offers it for custom
// groups only, and only empty ones — its entries would be stranded.
func (st *Store) DeleteSiteNavGroup(ctx context.Context, key string) error {
	_, err := st.db.ExecContext(ctx, `DELETE FROM site_nav_groups WHERE key = $1`, key)
	return err
}

// ── entries ─────────────────────────────────────────────────────────────

// ListSiteNav returns every entry, group-then-ordinal ordered.
func (st *Store) ListSiteNav(ctx context.Context) ([]NavEntry, error) {
	var out []NavEntry
	err := st.db.SelectContext(ctx, &out,
		`SELECT id, key, href, label, grp, ordinal, hidden, builtin
		   FROM site_nav ORDER BY grp, ordinal, label, id`)
	return out, err
}

// EnsureSiteNavKeyed inserts a builtin entry only if its key is absent.
func (st *Store) EnsureSiteNavKeyed(ctx context.Context, e NavEntry) error {
	_, err := st.db.ExecContext(ctx, `
		INSERT INTO site_nav (key, href, label, grp, ordinal, hidden, builtin)
		SELECT $1, $2, $3, $4, $5, $6, $7
		 WHERE NOT EXISTS (SELECT 1 FROM site_nav WHERE key = $1)`,
		e.Key, e.Href, e.Label, e.Grp, e.Ordinal, e.Hidden, e.Builtin)
	return err
}

// InsertSiteNav adds an operator row (key stays empty).
func (st *Store) InsertSiteNav(ctx context.Context, e NavEntry) error {
	_, err := st.db.ExecContext(ctx, `
		INSERT INTO site_nav (key, href, label, grp, ordinal, hidden, builtin)
		VALUES ('', $1, $2, $3, $4, $5, FALSE)`,
		e.Href, e.Label, e.Grp, e.Ordinal, e.Hidden)
	return err
}

// UpdateSiteNav rewrites one entry's editable fields by id.
func (st *Store) UpdateSiteNav(ctx context.Context, e NavEntry) error {
	_, err := st.db.ExecContext(ctx, `
		UPDATE site_nav SET label = $2, grp = $3, ordinal = $4, hidden = $5
		 WHERE id = $1`,
		e.ID, e.Label, e.Grp, e.Ordinal, e.Hidden)
	return err
}

// DeleteSiteNav removes one entry by id.
func (st *Store) DeleteSiteNav(ctx context.Context, id int64) error {
	_, err := st.db.ExecContext(ctx, `DELETE FROM site_nav WHERE id = $1`, id)
	return err
}

// DeleteSiteNavHref removes every entry linking to href — the pages editor's
// "no longer in a menu", which must catch both storeys.
func (st *Store) DeleteSiteNavHref(ctx context.Context, href string) error {
	_, err := st.db.ExecContext(ctx, `DELETE FROM site_nav WHERE href = $1 AND key = ''`, href)
	return err
}
